name: RandomChest
main: fabicorp.RandomChest
version: 1.1
commands: 
   rellenarcofres:
      description: Rellena cofres
      permission: randomchest.rellenarcofres
      permission-message: "No tienes permiso."
      usage: "/rellenarcofres Coord1X Coord1Y Coord1Z Coord2X Coord2Y Coord2Z Nivel_Cofres World"
   chestreload:
      description: Reinicia config RandomChest
      permission: randomchest.reload
      permission-message: "No tienes permiso."
      usage: "/reload"